services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: nextjsapp

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SITE_URL_ENV: ${SITE_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - SITE_URL=${SITE_URL}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
