apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: nextjs-app
  labels:
    app: nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: gchauhan1517/nextjs-app:latest  # Replace with your actual image
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: nextjs-config
              key: MONGO_URI
        - name: SITE_URL
          valueFrom:
            configMapKeyRef:
              name: nextjs-config
              key: SITE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: nextjs-app
  labels:
    app: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001  # For NodePort service
  type: NodePort  # Change to LoadBalancer if using cloud provider
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nextjs-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: your-domain.com  # Replace with your actual domain
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nextjs-service
#             port:
#               number: 3000
