---
- name: Update apt and install Docker & Jenkins prerequisites
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - fontconfig
    state: present
    force_apt_get: yes

- name: Install Java runtime for Jenkins (best-effort)
  apt:
    name: openjdk-17-jre
    state: present
  ignore_errors: true

- name: Create apt keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins apt repo
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/\n"
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Install Jenkins package
  apt:
    update_cache: yes
    name: jenkins
    state: present

- name: Install Docker prerequisites and Docker
  shell: |
    apt-get update -y
    apt-get install -y ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc || true
    chmod a+r /etc/apt/keyrings/docker.asc || true
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  args:
    creates: /usr/bin/docker

- name: Add ubuntu to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure jenkins group exists
  group:
    name: jenkins
    state: present

- name: Create jenkins user with /bin/false shell and add to docker group
  user:
    name: jenkins
    shell: /bin/false
    group: jenkins        # Primary group
    groups: docker        # Secondary group
    append: yes
    state: present

- name: Ensure services are enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker
    - jenkins
